config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'
 resources :cities do
  resources :posts
end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get "/users/:id/edit", to: "users#edit", as: "edit_user_profile"
  get "/users/:id", to: "users#show", as: "user_profile"
  patch "/users/:id", to: "users#update"
  put "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    after_action :allow_iframe, only: [:basic_embed, :awesome_embed]
    

    def new 
    @user = Current_user.new
    end

    def show
    @user = current_user
    end

    # edit
    def edit
    @user = current_user
    end

    # update
    def update
    @user = current_user
    @user.update(user_params)

    redirect_to user_profile_path(@user)
    end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :image, :location)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br />
<br />
<br />
<%= form_for(@user, url: user_profile_path) do |f| %>
  <legend>Edit User</legend>
    <fieldset>
      <div class="field-set">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name %>

        <%= f.label :image %>
        <%= f.text_field :image %>

          <%= f.label :location %>
        <%= f.text_field :location %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </fieldset>
<% end %>

app/views/users/show.html.erb
<br />
<br />

<div class="user-profile-container">
    <div class="user-profile-info">
        <h1>Hello, <%= @user.first_name %></h1>
        <% if @user.image %>
        <%= image_tag @user.image, size: "100x100" %>
        <% end %>
        <p>Name:</p>
        <p><%= @user.first_name%> <%= @user.last_name %></p>
        <p>Location:</p>
        <p><%= @user.location %>
        <%= link_to "edit", edit_user_profile_path(@user.id) %>
    </div>
    <div class="user-profile-posts">
        <% @user.posts.each do |post| %>
        <div class ="post-item-container">
            <% user = User.find(post.user_id) %>
            <div class="post-header">
            <% if user.image %>
                <div class="post-item-user-circle"><%= image_tag user.image %></div>
                <%else%>
                <div class="post-item-white-circle"></div>
            <%end%>
            <div class="post-header-info">
                <strong><%= post.title %></strong>
            </div>
            </div>
            <% if post.text.length > 1000 %>
            <p><%= post.text.truncate(997) %></p>
            <% else %>
            <p><%= post.text %></p>
            <% end %>
            <% city = post.city %>
            <%= link_to "view post", city_post_path(city, post) %>
            <p>Created <%= time_ago_in_words(post.created_at)%> ago<p>
        </div>
        <% end %>
    </div>
</div>