config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'
 resources :cities do
  resources :posts
end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get "/users/:id/edit", to: "users#edit", as: "edit_user_profile"
  get "/users/:id", to: "users#show", as: "user_profile"
  patch "/users/:id", to: "users#update"
  put "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :city

validates :title, presence: true
validates :text, presence: true
end
 

app/controllers/posts_controller.rb
    class PostsController < ApplicationController
        before_action :authenticate_user!
        load_and_authorize_resource  only: [:edit, :update, :destroy]
        after_action :allow_iframe, only: [:basic_embed, :awesome_embed]
        
      
        # GET /posts
        # GET /posts.json
        def index
          @posts = Post.all
        end

        # GET /posts/new
        def new
          @city = City.find params[:city_id]
          @post = Post.new

          @user = current_user
          @post = Post.new
        end
        
        # create
        def create
          @city = City.find params[:city_id]
          @user = current_user
          @post = @city.posts.create(post_params)
          @post.user_id = current_user.id
          @post.save

          redirect_to city_path(@city)
            
        end

        def show
          @user = current_user
          @post = Post.find(params[:id])
        end
      
        # GET /posts/1/edit
        def edit
          @city = City.find params[:city_id]
          @post = @city.posts.find(params[:id])
        end
      
        # update 
        def update
          @city = City.find params[:city_id]
          @post = @city.posts.find(params[:id])
          @post.update(post_params)
      
          redirect_to city_post_path(@city, @post)
        end
      
        # destroy
        def destroy
          @city = City.find params[:city_id]
          @post = Post.find(params[:id])
          @post.destroy
      
          redirect_to city_path(@city)
        end

  def user
    User.find(params[:user_id])
  end        
  private
    def post_params
      @user = current_user
      params.require(:post).permit(:title, :text, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<br />
<br />
<br />
<%= form_for [@city, @post] do |f| %>
<legend>Edit Post</legend>
  <fieldset>
    <div class="field-set">
      <%= f.label :title%>
      <%= f.text_field :title %>

      <%= f.label :text %>
      <%= f.text_area :text, size: '50x10' %>
    </div>
    <div class="actions">
      <%= f.submit class: "button" %>
    </div>
  </fieldset>
<% end %>

<%= form_for [@city, @post], method: :delete do |f| %>
<div class="actions">
  <%= f.submit "Delete!", class: "delete" %>
</div>
<% end %>

app/views/posts/index.html.erb
<h1>all posts Page</h1>

<h3>we don't need this view</h3>

app/views/posts/new.html.erb
<br />
<br />
<br />
<div class="create-new-post">
<div class="create-new-post-title"><!--New Post--></div>
<%=render "partials/post_form"%>
</div>

app/views/posts/show.html.erb
<div class="post-show-container">
    <div class="post-show-content">
        <h1><%= @post.title %></h1>

        <p><%= @post.text %></p>
        <div>
            <% if current_user != nil %>
                <% if @post.user_id == current_user.id %>
                    <%= link_to "edit", edit_city_post_path %>
                <%end %>
            <%end%>
        </div>
    </div>
</div>