config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'
 resources :cities do
  resources :posts
end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get "/users/:id/edit", to: "users#edit", as: "edit_user_profile"
  get "/users/:id", to: "users#show", as: "user_profile"
  patch "/users/:id", to: "users#update"
  put "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
     has_many :posts, dependent: :destroy
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  load_and_authorize_resource only: [:edit, :update, :destroy]
  after_action :allow_iframe, only: [:basic_embed, :awesome_embed]
  

  def index 
    @cities = City.all
  end
  #new 
  def new
    @user = current_user
    @city = City.new
  end

  # create
  def create
    @user = current_user
    @city = City.create!(city_params)

    
    redirect_to city_path(@city)
  end

  #show
  def show
    @city = City.find(params[:id])
  end

  # edit
  def edit
    @user = current_user
    @city = City.find(params[:id])
  end


  # update 
  def update
    @user = current_user
    @city = City.find(params[:id])
    @city.update(city_params)

    redirect_to city_path(@city)
  end

  # destroy
  def destroy
    @user = current_user
    @city = City.find(params[:id])
    @city.destroy

    redirect_to cities_path
  end

  private
  def city_params
    params.require(:city).permit(:name, :location, :image)
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/edit.html.erb
<br />
<br />
<br />

<h2>Edit City</h2>

<%= form_for @city do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

   <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit %>
<% end %>

<%= form_for @city, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/cities/index.html.erb
<br />

<p class="cities-index">Where do you want to visit?</p>
</div>
<% if user_signed_in? %>
<%= link_to "Add new city", new_city_path %>
<% end %>

<div class="city-list">
    <% @cities.each do |city| %>
    <a href="/cities/<%=city.id%>">
    <div style="background-image: url(<%= city.image %>);" class="city-list-element">
       <h3><%= city.name %></h3>
       <p><%= city.location %></p>
    </div></a>
    <% end %>
</div>

app/views/cities/new.html.erb
<div class="create-new-post-title"> Add a new City </div>

<%=render "partials/city_form"%>

app/views/cities/show.html.erb
<div style="background-image: url(<%= @city.image %>);" class="city-show-banner">
    <h1><%= @city.name %></h1>
    <div class="city-show-links">
        <% if user_signed_in? %>
        <%= link_to "edit", edit_city_path(@city.id) %>
        <% else %>
        <p> </p>
        <% end %>
        <p><%= @city.location %></p>
    </div>
</div>
<% if @city.posts.exists? %>
  <% if current_user == nil %>
    <div class="text-align-center"><h3><%= link_to "Log in", new_city_post_path(@city) %> to add a post for this city!</h3></div>
    <% else %>
    <div class="text-align-center"><h3><%= link_to "Add a Post", new_city_post_path(@city) %> for this city!</h3></div>
  <%end %>
<%else%>
  <% if current_user == nil %>
    <h3>No one has said anything about this city. Would you like to log in and <%= link_to "add a post", new_city_post_path(@city) %>?</h3>
  <% else %>  
    <h3>No one has said anything about this city. Would you like to <%= link_to "add a post", new_city_post_path(@city) %>?</h3>
  <%end%>
<%end%>
<div class="post-list-container">
  <% @city.posts.order(created_at: :desc).each do |post| %>
    <div class ="post-item-container">
      <% user = User.find(post.user_id) %>
      <div class="post-header">
        <% if user.image %>
          <div class="post-item-user-circle"><%= image_tag user.image %></div>
          <%else%>
          <div class="post-item-white-circle"></div>
        <%end%>
        <div class="post-header-info">
          <%if user.first_name && user.last_name %>
            <p><%= user.first_name %> <%=user.last_name %></p>
          <% else %>
            <p><%= user.email %></p>
          <% end %>
          <%= link_to "#{post.title}", city_post_path( @city, post) %>
        </div>
      </div>
      <% if post.text.length > 1000 %>
        <p><%= post.text.truncate(997) %></p>
        <% else %>
        <p><%= post.text %></p>
      <% end %>
      <p>Created <%= time_ago_in_words(post.created_at)%> ago<p>
    </div>
  <% end %>

</div>