config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'
 resources :cities do
  resources :posts
end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get "/users/:id/edit", to: "users#edit", as: "edit_user_profile"
  get "/users/:id", to: "users#show", as: "user_profile"
  patch "/users/:id", to: "users#update"
  put "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectVagabond</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="login">
        <div class="home-banner">
          <%= link_to "Project Globetrotter", cities_path %>
        </div>
          <div class='alerts'>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>
          <div class="login-container">
          <% if user_signed_in? %>

            <span>Welcome back, 
              <% if current_user.first_name %>
                <%= link_to current_user.first_name, user_profile_path(current_user.id)%></span>
              <% else %>
                <%= link_to current_user.email, user_profile_path(current_user.id)%></span>
              <% end %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log in", new_user_session_path %>
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
          </div>
          
      </div>
      <div class="main">
    <%= yield %>
    </div>
  </body>
</html>